### ISSUE TITLE
scp support

### ISSUE THREAD

**Issue by oomathias** [sjourdan/alpine-sshd#2]
It would be nice to have scp support.

Could you add `apk add openssh-client` to the image?

Thanks!

**Comment by sjourdan** [comment]
Why not. My goal was to build an easy entry point, something to ssh into, of drop files via sftp, but from outside. 
What's your use case like? You'd like be to be able to use scp right from inside the sshd container?

**Comment by oomathias** [comment]
I wanted to drop files with scp (not sftp) from the outside. And to do this, you actually need scp to be installed on the remote server too.

**Comment by sjourdan** [comment]
You're right! Wasn't my use case, but I'll add scp, as it will surely be useful.
